### ISSUE TITLE
Can you make it a template?

### ISSUE THREAD

**Issue by VMGuy23** [l1ttleO/ProjectFNF#22]
### What is your question?

Would be nice

**Comment by l1ttleO** [comment]
I won't do this because I heavily discourage modifying the source code of Psych and Psych-based projects. Modifying the source code makes your mod incompatible with vanilla Psych and ProjectFNF. Lua modding should be the standard in Psych Engine modding scene, any source code modifications should be reduced to the absolute minimum

**Comment by VMGuy23** [comment]
Psyche engine did it, and I want to have multiple reps based off ProjectFNF

**Comment by l1ttleO** [comment]
I do not want to fragment the modding scene by creating another "engine" for modders to use.

Starting from the original ProjectFNF 2.0 announcement, I've always pushed that this is *not* an engine for modders, it's an "engine for players". Using Psych Engine as a base for ProjectFNF was a good choice because of `mods` folder overhaul, which allows any mods originally developed for vanilla Psych to work on PFNF as well as long as the source code retains compatibility

The only thing modders can use from PFNF is some new options/modifiers
