### ISSUE TITLE
Crash with modded dialog 

### ISSUE THREAD

**Issue by zai205** [l1ttleO/ProjectFNF#41]
### Describe your bug here.

So I toyed olay the vs whitty definitive edition and it crashes after the opening animation

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I am using the vanilla and up to date versio. Of this

**Comment by l1ttleO** [comment]
I could not identify the cause of this crash, so I'm leaving it up to others to try and do so. Hint: it's not related to dialogues, it has something to do with countdowns and how `lo-fight`'s script manipulates them.

This _could_ be caused by https://github.com/l1ttleO/ProjectFNF/commit/2a7b4a6401b4572c16beef843393201cc0e6c59a, but it's likely that some code was lost in a Psych Engine update.

Anyway, the only way to prove one or the other is to try each release one-by-one until it starts working, then try each commit of that release until you narrow it down to a few lines of code (or lack thereof)

**Comment by zai205** [comment]
ok
